blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include


from .views import home_view

urlpatterns = [
   path('', home_view),
   path('admin/', admin.site.urls),
   path('polls/', include('polls.urls', namespace='polls')),
]

blog/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
   path('', views.question_list, name='question_list'),
   path('<int:question_id>/', views.question_detail, name='question_detail'),

]

blog/polls/models.py
from django.db import models

class Question(models.Model):
    qText = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    qType = models.BooleanField(default=False) #false - closed task, true - open task

class Choice(models.Model):
    question = models.ForeignKey(Question, models.CASCADE)
    choice_text = models.CharField(max_length=20)
    votes = models.IntegerField(0)

class Answer(models.Model):
    question = models.ForeignKey(Question, models.CASCADE)
    answer = models.CharField(max_length=20)

blog/todo/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=32)

class Task(models.Model):
    title = models.CharField(max_length=24)
    description = models.CharField(max_length=200)
    isDone = models.BooleanField()
    category = models.ForeignKey(Category, models.CASCADE)

blog/blog/views.py
from django.shortcuts import render

def home_view(request):
    return render(request, 'home.html')

blog/polls/views.py
from .models import Question
from django.shortcuts import render, get_object_or_404

def question_list(request):
   questions = Question.objects.all()
   return render(request, 'polls/question_list.html', {'questions': questions})

def question_detail(request, question_id):
   question = get_object_or_404(Question, pk=question_id)
   return render(request, 'polls/question_detail.html', {'question': question})

blog/todo/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/home.html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
    {% if user.is_authenticated %}
        <p>Hejka {{user}}</p>
    {% else %}
        <p>Nie jestes zalogowany</p>
    {% endif %}

    <div>
        <a href="{% url 'polls:question_list' %}">ankiety</a>
    </div>
</body>
</html>

blog/templates/polls/question_detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

blog/templates/polls/question_list.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'styles/qList.css' %}">
</head>
<body>
<div>
    <table>
        <tr>
            <th>id</th>
            <th>pytanie</th>
            <th>data</th>
        </tr>
        
    {% for question in questions %}
        <tr>
            <td>{{ question.id }}</td>
            <td><a href="{% url 'polls:question_detail' question.id %}">{{ question.question_text }}</a></td>
            <td>{{ question.pub_date }}</td>
        </tr>
    {% endfor %}
    </table>
</div>
</body>
</html>